services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dms_user
      POSTGRES_PASSWORD: dms_password
      POSTGRES_DB: dms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5      
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app_network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3      
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
