global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["192.168.1.18:9113"] # Replace 'nginx' with the server's IP

  - job_name: "backend"
    static_configs:
      - targets:
        - backend1:8080
        - backend2:8080
